### PR TITLE
Ported to macOS

### LINKED ISSUE #83: sockperf will not compile on macOS
Attempting to compile this on macOS 10.12 with autoconf, etc. installed, I run into this issue:
```
In file included from src/aopt.cpp:33:
src/os_abstract.h:138:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^
1 error generated.
make[2]: *** [src/aopt.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
I used this gist for endian.h and put it into /usr/include: https://gist.github.com/yinyin/2027912

Then I get this error:
```
In file included from src/aopt.cpp:33:
src/os_abstract.h:193:2: error: unknown type name 'cpu_set_t'
        cpu_set_t cpuset;
        ^
1 error generated.
make[2]: *** [src/aopt.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by Pusnow**
Hi,

I ported sockperf to macOS.
To do so, I changed the followings.

Resolves #83 

### 1. Change the `version` file to `sockperf-version`.

In my machine (macOS 13.1, Apple M1 (arm64), AppleClang 14.0.0), when I tried to build sockperf, the `version` file conflicted with C++20's version header (https://en.cppreference.com/w/cpp/header/version). The version header is used in the macOS's C++ std library, and an error occurs when the library tries to include the version header.
So I changed the `version`'s filename to `sockperf-version`.

### 2. Change `struct sockaddr_store_t`'s `ss_family` to `addr`.

```c
struct sockaddr_store_t {
    union {
        sockaddr addr; // was  sa_family_t ss_family;
        sockaddr_in addr4;
        sockaddr_in6 addr6;
        sockaddr_un addr_un;
    };
};
```

In macOS, the first member of `sockaddr_*` structures is not `sa_family_t` (https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/netinet/in.h#L397-L403).
So to access `ss_family` correctly in a portable way, I changed the member `ss_family` to `sockaddr addr` and all codes accessing it.

 
### 3. Add macOS-specific a thread affinity implementation

Unlike other parts of `os_abstract`, the thread affinity codes are not compatible with macOS, so I implement macOS-specific thread affinity functions.
However, macOS's thread affinity API has a different behavior from the other OSes.
In macOS, it is impossible to "pin" threads to specific cores, and rather application gives a tag (or hint) to the OS scheduler, and threads with the same affinity tag will be scheduled to share an L2 cache if possible. 
In this implementation, if a user gives thread affinity information, sockperf only gives a tag (only the last core id) to threads.

See https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/osfmk/mach/thread_policy.h#L186-L202 for more detail.

### 4. Some misc changes

I also changed argument parsing and `vma_xlio` parts to port sockperf to macOS.

### CODE REVIEW

**Comment by ghost** [comment]
Can one of the admins verify this patch?

File: src/ip_address.h [hunk 1]
```diff
@@ -38,6 +38,11 @@
 #include <afunix.h>
 typedef unsigned short int sa_family_t;
 
+#elif __APPLE__
+#include <sys/socket.h>
+#include <netinet/in.h>
+#include <sys/un.h>      /* definitions for UNIX domain sockets */
+
```
Comment (igor-ivanov) [inline src/ip_address.h:45]: please consider using one section in case no difference for `linux` and `macos` as
`#elif defined(__linux__) || defined(__APPLE__) `

File: src/vma-xlio-redirect.h [hunk 2]
```diff
@@ -40,6 +40,9 @@
 #ifdef __FreeBSD__
 #include <netinet/in.h>
 #include <stdio.h>
+#elif __APPLE__
+#include <netinet/in.h>
+#include <stdio.h>
```
Comment (igor-ivanov) [inline src/vma-xlio-redirect.h:43]: please consider using one section in case no difference for `linux` and `macos` as
`#elif defined(__linux__) || defined(__APPLE__) `

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by Pusnow** [comment]
Hi,I've updated the codes.

File: src/ip_address.h [hunk 3]
```diff
@@ -38,12 +38,7 @@
 #include <afunix.h>
 typedef unsigned short int sa_family_t;
 
-#elif __APPLE__
-#include <sys/socket.h>
-#include <netinet/in.h>
-#include <sys/un.h>      /* definitions for UNIX domain sockets */
-
-#elif __linux__
+#elif defined(__linux__) || defined(__APPLE__)
```
Comment (agalanin-at-nvidia) [inline src/ip_address.h:41]: please mark the corresponding `#endif` with comment `__windows__, __linux__, __APPLE__` to make it easier to locate

File: src/os_abstract.cpp [hunk 4]
```diff
@@ -398,6 +405,9 @@ int os_get_max_active_fds_num() {
             return 1024; // try the common default
         }
         max_active_fd_num = (int)curr_limits.rlim_max;
+        if (max_active_fd_num == -1){
```
Comment (agalanin-at-nvidia) [inline src/os_abstract.cpp]:
```suggestion
        if (max_active_fd_num == -1) {
```

File: src/ip_address.h (hunk 3 above)
Comment (agalanin-at-nvidia) [reply src/ip_address.h:41]: could you please apply this comment to all `#ifdef`s affected by your change?

Comment (Pusnow) [reply src/ip_address.h:41]: Updated!

**Review by agalanin-at-nvidia — APPROVED** [review]
OK for me!
Please squash today's small changes into previous commits to make history shorter because we're using "rebase" model for merging pull requests into a master branch.

**Comment by Pusnow** [comment]
Done!

**Comment by igor-ivanov** [comment]
@Pusnow There is compilation failure when enabling extra api.

Compilation error:
src/sockperf.cpp: In function ‘bool is_unspec_addr(const sockaddr_store_t&)’:
src/sockperf.cpp:3068:18: error: ‘const struct sockaddr_store_t’ has no member named ‘ss_family’
     switch (addr.ss_family) {
                  ^~~~~~~~~
make[2]: *** [Makefile:688: src/sockperf.o] Error 1
make[2]: *** Waiting for unfinished jobs....

Note:
configure --prefix=$PWD/install --enable-extra-api CPPFLAGS=-I<path to libvma installation>
libvma: https://github.com/Mellanox/libvma/

**Comment by Pusnow** [comment]
I fixed the compilation error. Would you verify the patch?

**Comment by igor-ivanov** [comment]
Thanks, could you combine commit 5 with 2 and commit 4 with 3 to have following list of changes as
[Change version file's name to sockperf-version]
[Ported to macOS]
[Ported to macOS (misc parts)]

**Comment by Pusnow** [comment]
Sure, I've merged the commits.

**Review by igor-ivanov — APPROVED** [review]
